// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go SMTP Micro Service
A smtp service for golang


    Schemes:
      http
    Host: localhost
    BasePath: /v1/gosmtp
    Version: 1.0
    Contact: Shivang Goswami<shivang.goswami@outlook.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
