// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A smtp service for golang",
    "title": "Go SMTP Micro Service",
    "contact": {
      "name": "Shivang Goswami",
      "email": "shivang.goswami@outlook.com"
    },
    "version": "1.0"
  },
  "basePath": "/v1/gosmtp",
  "paths": {
    "/sendmail": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "send email rest api",
        "tags": [
          "Smtp"
        ],
        "summary": "send e-mail",
        "parameters": [
          {
            "name": "inputParam",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/inputParam"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generic success response",
            "schema": {
              "$ref": "#/definitions/status"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      },
      "x-visibility": "public"
    },
    "inputParam": {
      "type": "object",
      "required": [
        "subject",
        "customId",
        "from"
      ],
      "properties": {
        "bcc": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        },
        "cc": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        },
        "customId": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/person"
        },
        "html": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "to": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        }
      },
      "x-visibility": "public"
    },
    "person": {
      "type": "object",
      "required": [
        "name",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      },
      "x-visibility": "public"
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-api",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations related to Smtp",
      "name": "Smtp"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A smtp service for golang",
    "title": "Go SMTP Micro Service",
    "contact": {
      "name": "Shivang Goswami",
      "email": "shivang.goswami@outlook.com"
    },
    "version": "1.0"
  },
  "basePath": "/v1/gosmtp",
  "paths": {
    "/sendmail": {
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "send email rest api",
        "tags": [
          "Smtp"
        ],
        "summary": "send e-mail",
        "parameters": [
          {
            "name": "inputParam",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/inputParam"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generic success response",
            "schema": {
              "$ref": "#/definitions/status"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      },
      "x-visibility": "public"
    },
    "inputParam": {
      "type": "object",
      "required": [
        "subject",
        "customId",
        "from"
      ],
      "properties": {
        "bcc": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        },
        "cc": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        },
        "customId": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/person"
        },
        "html": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "to": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/person"
          }
        }
      },
      "x-visibility": "public"
    },
    "person": {
      "type": "object",
      "required": [
        "name",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      },
      "x-visibility": "public"
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-api",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations related to Smtp",
      "name": "Smtp"
    }
  ]
}`))
}
